name: apidash_mcp
description: Model Context Protocol (MCP) server for ApiDash.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.1

resolution: workspace

executables:
  apidash_mcp: mcp

# Add regular dependencies here.
dependencies:
  apidash_cli: any
  dart_mcp: ^0.5.0
  mcp_dart: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
